COMPOUND = (
    (1, "People Square"),
    (2, "Zhongshan Park"),
    (3, "Xin Tian Di"),
    (4, "Expo Area"),
)
AREA=(
    (1, "Bund Area"),
    (2, "Expo Area"),
    (3, "Gubei"),
    (4, "Hongkou"),
    (5, "Hongqiao"),
    (6, "Jing An"),
    (7, "Jingqao"),
    (8, "Minhang"),
    (9, "Old Town"),
    (10, "People's Square"),
    (11, "Pudong"),
    (12, "Putuo"),
    (13, "Qingpu"),
    (14, "Suzhou Creek"),
    (15, "Xintiandi"),
    (16, "Xuhui"),
    (17, "Xujiahui"),
    (18, "Yangpu(Fudan/Tonji)"),
    (19, "Zhabei"),
    (20, "Zhongshan Park"),
)
