# coding: utf-8
COMPOUND = (
    (0, "Please Choose"),
    (1, "People Square"),
    (2, "Zhongshan Park"),
    (3, "Xin Tian Di"),
    (4, "Expo Area"),
)
AREA=(
    ('', "Please Choose"),
    (1, "Bund Area外滩"),
    (2, "Expo Area世博园区"),
    (3, "Gubei古北"),
    (4, "Hongkou虹口"),
    (5, "Hongqiao虹桥"),
    (6, "Jing An静安"),
    (7, "Jinqiao金桥"),
    (8, "Minhang闵行"),
    (9, "Old Town老城区"),
    (10, "People’s Square人民广场"),
    (11, "Pudong浦东"),
    (12, "Putuo普陀"),
    (13, "Qingpu青浦"),
    (14, "Suzhou Greek苏州河"),
    (15, "Xiantiandi新天地"),
    (16, "Xujiahui徐家汇"),
    (17, "Yangpu杨浦（复旦/同济）"),
    (18, "Zhabei闸北"),
    (19, "Zhongshan Park中山公园"),
)
